name: Fast-API CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  test-model-api:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train models
      run: |
        cd ./src/model/ && python train.py && cd ..
        cd ..

    - name: Run tests
      run: |
        pytest